import React from "react";
import Head from "next/head";


const about = () => {
  return (
    <div>
      <Head>
        <title>About Dungys Liquor</title>
        <meta name="description" content="Generated by Erick Munoz" />
      </Head>
      
      <h1>ABOUT PAGE </h1>
    </div>
  );
};

export default about;
