import React from "react";
import Head from "next/head";


const contact = () => {
  return (
    <div>
      <Head>
        <title>Contact Dungys Liquor</title>
        <meta name="description" content="Generated by Erick Munoz" />
      </Head>
      
      <h1>Contact PAGE </h1>
    </div>
  );
};

export default contact;
